table 'Totales VMD'
	lineageTag: cf5968c0-b073-433f-bcff-34f7d9a97a5d

	measure CrecimientoVelocidad = ```
			
			VAR VelocidadActual = CALCULATE(
			    AVERAGE('Totales VMD'[Mbps (Media de bajada)]),
			    'Totales VMD'[Año] = 2023
			)
			VAR VelocidadAnterior = CALCULATE(
			    AVERAGE('Totales VMD'[Mbps (Media de bajada)]),
			    'Totales VMD'[Año] = 2022
			)
			RETURN 
			DIVIDE(
			    VelocidadActual - VelocidadAnterior,
			    VelocidadAnterior
			) * 100
			
			```
		lineageTag: 46e012a3-aeff-4453-b0c5-b8c866b30aed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure KPI2 =
			
			AVERAGE('Totales VMD'[Mbps (Media de bajada)])+'Totales VMD'[CrecimientoVelocidad]
		lineageTag: de00783c-2d6c-4609-9c37-364c5f8be4e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Año
		dataType: int64
		formatString: 0
		lineageTag: e24cce9b-e5f0-4319-b992-1bbbf42154a7
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 6a15845c-7f64-4ab6-866c-c9a8bfcb9af0
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Mbps (Media de bajada)'
		dataType: double
		lineageTag: c7c90f18-b856-4559-a93d-23bec7b3f319
		summarizeBy: sum
		sourceColumn: Mbps (Media de bajada)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Trimestre_1
		dataType: string
		lineageTag: 30c6c09f-f21f-4c60-b2cd-50ff274c07ad
		summarizeBy: none
		sourceColumn: Trimestre_1

		annotation SummarizationSetBy = Automatic

	partition 'Totales VMD' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rubio\Documents\SoyHenry\Proyecto_Individual\Internet.xlsx"), null, true),
				    #"Totales VMD_Sheet" = Origen{[Item="Totales VMD",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Totales VMD_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Año", Int64.Type}, {"Trimestre", Int64.Type}, {"Mbps (Media de bajada)", type number}, {"Trimestre_1", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

